spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dbkali2023
    username: root
    password: 123456

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        hbm2ddl:
          auto: update

  show-sql: true

server:
  port: 8080
